// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVS0ergc8DIZXmBUzwxhzNoqPKTXJq3T8',
    appId: '1:963004586146:web:4cce41f6850924416cdffb',
    messagingSenderId: '963004586146',
    projectId: 'ariam-handcraft',
    authDomain: 'ariam-handcraft.firebaseapp.com',
    storageBucket: 'ariam-handcraft.appspot.com',
    measurementId: 'G-6V4NMDNZ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfLIfad7bdIQ9MWREIY8ObMBERfn0LWC8',
    appId: '1:963004586146:android:97e5ed27816cbbac6cdffb',
    messagingSenderId: '963004586146',
    projectId: 'ariam-handcraft',
    storageBucket: 'ariam-handcraft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8TsuxKNglMkg4xn-CnqKqx9I7J2W7Eho',
    appId: '1:963004586146:ios:aaea6eb1655e913e6cdffb',
    messagingSenderId: '963004586146',
    projectId: 'ariam-handcraft',
    storageBucket: 'ariam-handcraft.appspot.com',
    iosClientId: '963004586146-oahkupavce3l9d8tj98sl7lngn0l504g.apps.googleusercontent.com',
    iosBundleId: 'com.abdullah.ariam.handcraft.ariamHandcraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8TsuxKNglMkg4xn-CnqKqx9I7J2W7Eho',
    appId: '1:963004586146:ios:aaea6eb1655e913e6cdffb',
    messagingSenderId: '963004586146',
    projectId: 'ariam-handcraft',
    storageBucket: 'ariam-handcraft.appspot.com',
    iosClientId: '963004586146-oahkupavce3l9d8tj98sl7lngn0l504g.apps.googleusercontent.com',
    iosBundleId: 'com.abdullah.ariam.handcraft.ariamHandcraft',
  );
}
