import 'package:ariam_handcraft/shared/component/strings.dart';

import '../../models/category_model.dart';
import '../../models/prodcuts_model.dart';
import '../style/image_strings.dart';

List<ProductModel> testProducts = [
  ProductModel(
      docID: "1",
      adminID: "",
      name: "ايس كاب",
      admin: "admin",
      categoryId: crochet,
      description: "شغل يدوي",
      discount: 0,
      imagePath: "",
      img: imageCrochet,
      isDiscount: false,
      price: 125,
      adminState: "admin",
      dayToDelivery: "10"),
  ProductModel(
      docID: "7",imagePath: "",
      adminID: "",
      name: "حفل خطوبة",
      categoryId: planner,
      description: "شغل يدوي",
      discount: 6,
      admin: "admin",
      img: imagePlanner,
      isDiscount: true,
      price: 655,
      adminState: "admin",
      dayToDelivery: "10"),
  ProductModel(
      docID: "2",
      adminID: "",imagePath: "",
      admin: "admin",
      name: "بلوفر",
      categoryId: crochet,
      description: "شغل يدوي",
      discount: 10,
      img: imageCrochet,
      isDiscount: true,
      price: 522,
      adminState: "admin",
      dayToDelivery: "10"),
  ProductModel(
      docID: "3",
      name: "كوفيه",
      adminID: "",imagePath: "",
      admin: "admin",
      categoryId: crochet,
      description: "شغل يدوي",
      discount: 5,
      img: imageCrochet,
      isDiscount: true,
      price: 852,
      adminState: "admin",
      dayToDelivery: "10"),
  ProductModel(
      docID: "5",
      name: "شنط",
      adminID: "",
      admin: "admin",
      categoryId: crochet,
      description: "شغل يدوي",
      discount: 10,imagePath: "",
      img: imageCrochet,
      isDiscount: true,
      adminState: "admin",
      price: 655,
      dayToDelivery: "10"),
  ProductModel(
      docID: "4",
      adminID: "",
      name: "حلق",
      categoryId: accessories,
      admin: "admin",imagePath: "",
      description: "شغل يدوي",
      adminState: "admin",
      discount: 0,
      img: imageAcc,
      isDiscount: false,
      price: 126,
      dayToDelivery: "10"),
  ProductModel(
      docID: "6",
      admin: "admin",
      adminID: "",
      name: "بلوفر اطفال",imagePath: "",
      categoryId: crochet,
      description: "شغل يدوي",
      adminState: "admin",
      discount: 7,
      img: imageCrochet,
      isDiscount: true,
      price: 655,
      dayToDelivery: "10"),
  ProductModel(
      docID: "8",
      name: "سبوع",
      adminID: "",imagePath: "",
      admin: "admin",
      adminState: "admin",
      categoryId: planner,
      description: "شغل يدوي",
      discount: 5,
      img: imagePlanner,
      isDiscount: true,
      price: 655,
      dayToDelivery: "10"),
  ProductModel(
      docID: "9",
      adminState: "admin",
      name: "بوكيه فرح",
      admin: "admin",
      adminID: "",imagePath: "",
      categoryId: bouquet,
      description: "شغل يدوي",
      discount: 10,
      img: imageBouquet,
      isDiscount: true,
      price: 655,
      dayToDelivery: "10"),
  ProductModel(
      docID: "10",
      name: "شال",
      adminState: "admin",
      adminID: "",imagePath: "",
      admin: "admin",
      categoryId: crochet,
      description: "شغل يدوي",
      discount: 0,
      img: imageCrochet,
      isDiscount: false,
      price: 655,
      dayToDelivery: "10"),
];

List<CategoryModel> testCategory = [
  CategoryModel(
      categoryId: "1", categoriesName: crochet, categoryImg: imageCrochet),
  CategoryModel(
      categoryId: "2", categoriesName: bouquet, categoryImg: imageBouquet),
  CategoryModel(
      categoryId: "3", categoriesName: planner, categoryImg: imagePlanner),
  CategoryModel(
      categoryId: "4", categoriesName: accessories, categoryImg: imageAcc),
];
